//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract_Management.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityMaster
    {
        public long ActivityId { get; set; }
        public string ActivityName { get; set; }
        public string ActionName { get; set; }
        public string Role { get; set; }
        public string Actioner { get; set; }
        public Nullable<bool> IsDepartment { get; set; }
    }
}
