//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract_Management.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long EMP_ID { get; set; }
        public string PO_NUM { get; set; }
        public string EMP_NAME { get; set; }
        public string GENDER { get; set; }
        public string MARITAL_STATUS { get; set; }
        public Nullable<bool> HAVING_ESI_NO { get; set; }
        public string ESI_EXEMPTED_CASE { get; set; }
        public string EMP_ESINO { get; set; }
        public Nullable<System.DateTime> ESI_REGN_DATE { get; set; }
        public string ESI_NOMINEE_NAME { get; set; }
        public Nullable<bool> PEHCHAN { get; set; }
        public string EMP_PF_NO { get; set; }
        public Nullable<System.DateTime> PF_REGN_DATE { get; set; }
        public string UAN { get; set; }
        public Nullable<bool> EPS { get; set; }
        public Nullable<bool> EVICTEE { get; set; }
        public string EVICTEE_CARD_NO { get; set; }
        public Nullable<bool> ISMW { get; set; }
        public string DISABILITY_TYPE { get; set; }
        public string NOMINEE_RELATIONSHIP_TYPE { get; set; }
        public string NOMINEE_RELATION_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string PRESENT_ADRS { get; set; }
        public string PERMANENT_ADRS { get; set; }
        public string CITY { get; set; }
        public string DISTRICT { get; set; }
        public string STATE { get; set; }
        public string PINCODE { get; set; }
        public string MOBILE_NO { get; set; }
        public Nullable<bool> WAGE_ABOVE_15000 { get; set; }
        public Nullable<bool> PF_EARLIER_MEMBER { get; set; }
        public Nullable<bool> WAGE_ABOVE_21000 { get; set; }
        public string WC_POLICY_NO { get; set; }
        public Nullable<System.DateTime> WC_POLICY_FROM_DATE { get; set; }
        public Nullable<System.DateTime> WC_POLICY_TO_DATE { get; set; }
        public Nullable<int> NO_COVERED_UNDER_WC_POLICY { get; set; }
        public string WORK_TYPE { get; set; }
        public string EMP_TYPE { get; set; }
        public Nullable<decimal> MONTHLY_WAGES { get; set; }
        public string ID_TYPE { get; set; }
        public string AADHAR_NO { get; set; }
        public byte[] PHOTO { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_BRANCH { get; set; }
        public string BANK_ADDRESS { get; set; }
        public string BANK_ACNO { get; set; }
        public string BANK_IFSC { get; set; }
        public Nullable<bool> BLACK_LISTED { get; set; }
        public string BLACK_LISTED_REASON { get; set; }
        public Nullable<System.DateTime> BLACK_LISTED_DATE { get; set; }
        public string REMARKS { get; set; }
        public string DECLARATION { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_ON { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
