//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract_Management.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Servicebook
    {
        public long ID { get; set; }
        public long EMP_ID { get; set; }
        public string JOB_ID { get; set; }
        public string ESI_EXEMPTION { get; set; }
        public string WC_POLICY { get; set; }
        public Nullable<System.DateTime> WC_POLICY_VALID_UPTO { get; set; }
        public string PF_EXEMPTION { get; set; }
        public string EMP_ESINO { get; set; }
        public string EMPR_ESI_CODE { get; set; }
        public string EMP_PF_NO { get; set; }
        public string UAN_NO { get; set; }
        public string EMPR_PF_CODE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
    }
}
