//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract_Management.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Doc
    {
        public long TRANS_ID { get; set; }
        public string VENDOR_CODE { get; set; }
        public Nullable<long> PO_NUMBER { get; set; }
        public Nullable<long> EMPLOYEE_ID { get; set; }
        public Nullable<long> DOC_ID { get; set; }
        public string DOC_EXTN { get; set; }
        public byte[] DOCUMENT { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
