//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract_Management.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_ARC1
    {
        public int COMP_ID { get; set; }
        public string ARC_ID { get; set; }
        public Nullable<int> DEPT_ID { get; set; }
        public string CONT_ID { get; set; }
        public string JOB_NAME { get; set; }
        public Nullable<System.DateTime> ARC_DATE { get; set; }
        public string ARC_DETAILS { get; set; }
        public System.DateTime ARC_FROM { get; set; }
        public System.DateTime ARC_TO { get; set; }
        public Nullable<System.DateTime> DEACTIVATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_ON { get; set; }
    }
}
