//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract_Management.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Arc
    {
        public long ARC_ID { get; set; }
        public string ARC_NO { get; set; }
        public string PO_NUM { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> ARC_DATE { get; set; }
        public Nullable<System.DateTime> SCHEDULE_FROM { get; set; }
        public Nullable<System.DateTime> SCHEDULE_TO { get; set; }
        public Nullable<System.DateTime> DEACTIVATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
    }
}
