//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract_Management.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public long MenuId { get; set; }
        public string MenuName { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<long> RoleId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
